# Generated by Django 3.0.5 on 2020-05-01 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transaction_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payee_id', models.CharField(max_length=50)),
                ('payer_id', models.CharField(max_length=50)),
                ('transaction_timestamp', models.DateTimeField()),
                ('location', models.CharField(max_length=20)),
                ('transaction_status', models.CharField(max_length=10)),
                ('transaction_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='roundoff_transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_offset', models.IntegerField()),
                ('roundoff_amt', models.DecimalField(decimal_places=2, max_digits=20)),
                ('roundoff_trans_id', models.CharField(max_length=50)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction_details')),
            ],
        ),
    ]
